apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-nodejs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    #### IP gluster svc nfs
    server: 10.92.6.13
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-nodejs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-nodejs-pvc
# spec:
#   storageClassName: demo-nodejs-storageclass
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-nodejs-pvc
#   # annotations:
#   # volume.beta.kubernetes.io/storage-class: demo-nodejs-storageclass
# spec:
#   storageClassName: demo-nodejs-storageclass
#   volumeName: demo-nodejs-pv
#   resources:
#     requests:
#       storage: 1Gi
#   accessModes:
#     - ReadWriteOnce