apiVersion: v1
kind: Service
metadata:
  name: demo-redis-service
spec:
  selector:
    app: demo-redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-redis
  labels:
    app: demo-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-redis
  template:
    metadata:
      labels:
        app: demo-redis
    spec:
      containers:
      - name: demo-redis
        # image: bitnami/redis:latest
        image: redis
        ports:
        - containerPort: 6379
          name: demo-redis
        imagePullPolicy: Always
        args: ["--requirepass", "$(REDIS_PASSWORD)"] #Set mật khẩu redis
        # command:
        #   - redis-server
        # args:
        #   - --requirepass
        #   - ${REDIS_PASSWORD}
        # envFrom:
        #   - secretRef:
        #       name: demo-redis-secret
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-redis-secret
                key: REDIS_PASSWORD
        
