apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: redis-2
  name: redis-2
spec: 
  clusterIP: None
  ports:
  - name: redis-2-service
    port: 6379
    targetPort: 6379
  selector: 
    app: redis-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-2
  labels:
    app: redis-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-2
  template:
    metadata:
      labels:
        app: redis-2
    spec:
      containers:
      - name: redis-2
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis-2