apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-develop
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-develop
  template:
    metadata:
      labels:
        role: nfs-server-develop
    spec:
      containers:
      - name: nfs-server-develop
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc-develop
      volumes:
        - name: mypvc-develop
          gcePersistentDisk:
            pdName: nfs-disk-develop-0
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-develop-service
spec:
  # clusterIP 10.3.240.20
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server-develop
