apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-nodejs-develop-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    #### IP gluster svc nfs
    server: 10.56.1.85
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-nodejs-develop-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi