apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-nodejs-storageclass
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-ssd
  fstype: ext4
  replication-type: none