kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-test-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/postgres-test"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-test-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi