apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-certificate
  namespace: default
spec:
  secretName: motbay.ga-certificate-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: motbay.ga
  dnsNames:
  - motbay.ga
  - www.motbay.ga

